import type { Client, Task } from "@/types";
import type { GmailThread } from "@/hooks/use-communications";

const now = () => new Date();
const days = (n: number) => {
  const d = now();
  d.setDate(d.getDate() + n);
  return d;
};
const hours = (n: number) => {
  const d = now();
  d.setHours(d.getHours() + n);
  return d;
};

export const placeholderClients: Client[] = [
  {
    id: "ph-client-1",
    name: "Acme Corp",
    status: "active",
    primary_contact_name: "Jane Doe",
    primary_contact_email: "jane@acme.example",
    notes: null,
    created_at: now().toISOString(),
  },
  {
    id: "ph-client-2",
    name: "Globex Industries",
    status: "active",
    primary_contact_name: "John Smith",
    primary_contact_email: "john@globex.example",
    notes: null,
    created_at: now().toISOString(),
  },
  {
    id: "ph-client-3",
    name: "Initech",
    status: "active",
    primary_contact_name: "Peter Gibbons",
    primary_contact_email: "peter@initech.example",
    notes: null,
    created_at: now().toISOString(),
  },
  {
    id: "ph-client-4",
    name: "Hooli",
    status: "active",
    primary_contact_name: "Gavin Belson",
    primary_contact_email: "gavin@hooli.example",
    notes: null,
    created_at: now().toISOString(),
  },
];

const acme = { id: "ph-client-1", name: "Acme Corp" };
const globex = { id: "ph-client-2", name: "Globex Industries" };
const initech = { id: "ph-client-3", name: "Initech" };
const hooli = { id: "ph-client-4", name: "Hooli" };

export const placeholderTasks: Task[] = [
  {
    id: "ph-task-1",
    title: "Finalize Q1 Report and Presentation",
    description: "Pull KPI numbers, assemble the slide deck, send for review.",
    status: "active",
    type: "main",
    priority: "high",
    assignee_id: null,
    client_id: acme.id,
    parent_task_id: null,
    deadline: days(2).toISOString(),
    est_effort_minutes: 12 * 60 + 30,
    action_date: hours(2).toISOString(),
    notification_at: hours(20).toISOString(),
    created_by: null,
    created_at: days(-3).toISOString(),
    updated_at: days(-1).toISOString(),
    client: acme,
  },
  {
    id: "ph-task-2",
    title: "Onboarding call with Globex stakeholders",
    description: null,
    status: "active",
    type: "main",
    priority: "normal",
    assignee_id: null,
    client_id: globex.id,
    parent_task_id: null,
    deadline: days(1).toISOString(),
    est_effort_minutes: 60,
    action_date: hours(6).toISOString(),
    notification_at: hours(24).toISOString(),
    created_by: null,
    created_at: days(-2).toISOString(),
    updated_at: days(-1).toISOString(),
    client: globex,
  },
  {
    id: "ph-task-3",
    title: "Reply to Initech support thread",
    description: "Customer reported a broken login flow.",
    status: "active",
    type: "main",
    priority: "critical",
    assignee_id: null,
    client_id: initech.id,
    parent_task_id: null,
    deadline: hours(-2).toISOString(),
    est_effort_minutes: 30,
    action_date: hours(-2).toISOString(),
    notification_at: hours(-2).toISOString(),
    created_by: null,
    created_at: days(-1).toISOString(),
    updated_at: days(-1).toISOString(),
    client: initech,
  },
  {
    id: "ph-task-4",
    title: "Review renewal contract for Hooli",
    description: "Legal flagged terms — sign-off needed.",
    status: "pending",
    type: "main",
    priority: "high",
    assignee_id: null,
    client_id: hooli.id,
    parent_task_id: null,
    deadline: days(5).toISOString(),
    est_effort_minutes: 90,
    action_date: days(3).toISOString(),
    notification_at: days(4).toISOString(),
    created_by: null,
    created_at: days(-5).toISOString(),
    updated_at: days(-1).toISOString(),
    client: hooli,
  },
  {
    id: "ph-task-5",
    title: "Schedule weekly sync with Acme team",
    description: null,
    status: "reminder",
    type: "main",
    priority: "low",
    assignee_id: null,
    client_id: acme.id,
    parent_task_id: null,
    deadline: days(7).toISOString(),
    est_effort_minutes: 15,
    action_date: days(6).toISOString(),
    notification_at: days(7).toISOString(),
    created_by: null,
    created_at: days(-2).toISOString(),
    updated_at: days(-2).toISOString(),
    client: acme,
  },
  {
    id: "ph-task-6",
    title: "Draft email response template for billing",
    description: "First-pass copy for the team to review.",
    status: "draft",
    type: "main",
    priority: "normal",
    assignee_id: null,
    client_id: null,
    parent_task_id: null,
    deadline: null,
    est_effort_minutes: 45,
    action_date: null,
    notification_at: null,
    created_by: null,
    created_at: days(-1).toISOString(),
    updated_at: days(-1).toISOString(),
    client: null,
  },
  {
    id: "ph-task-7",
    title: "Daily team work summary for MySigrid",
    description: null,
    status: "active",
    type: "main",
    priority: "normal",
    assignee_id: null,
    client_id: globex.id,
    parent_task_id: null,
    deadline: hours(8).toISOString(),
    est_effort_minutes: 60,
    action_date: hours(2).toISOString(),
    notification_at: hours(8).toISOString(),
    created_by: null,
    created_at: hours(-12).toISOString(),
    updated_at: hours(-1).toISOString(),
    client: globex,
  },
  {
    id: "ph-task-8",
    title: "Plan all-hands agenda",
    description: null,
    status: "active",
    type: "main",
    priority: "normal",
    assignee_id: null,
    client_id: null,
    parent_task_id: null,
    deadline: days(7).toISOString(),
    est_effort_minutes: 30,
    action_date: days(6).toISOString(),
    notification_at: days(7).toISOString(),
    created_by: null,
    created_at: days(-1).toISOString(),
    updated_at: days(-1).toISOString(),
    client: null,
  },
  {
    id: "ph-task-9",
    title: "Q4 retrospective notes",
    description: "Closed out last quarter — reference material.",
    status: "closed",
    type: "main",
    priority: "normal",
    assignee_id: null,
    client_id: hooli.id,
    parent_task_id: null,
    deadline: days(-14).toISOString(),
    est_effort_minutes: 120,
    action_date: days(-15).toISOString(),
    notification_at: days(-14).toISOString(),
    created_by: null,
    created_at: days(-30).toISOString(),
    updated_at: days(-14).toISOString(),
    client: hooli,
  },
  {
    id: "ph-task-10",
    title: "Audit pending invoices for Initech",
    description: null,
    status: "pending",
    type: "main",
    priority: "high",
    assignee_id: null,
    client_id: initech.id,
    parent_task_id: null,
    deadline: days(3).toISOString(),
    est_effort_minutes: 90,
    action_date: days(2).toISOString(),
    notification_at: days(3).toISOString(),
    created_by: null,
    created_at: days(-2).toISOString(),
    updated_at: days(-1).toISOString(),
    client: initech,
  },
];

const t = (offsetSeconds: number) => Math.floor(Date.now() / 1000) + offsetSeconds;

export const placeholderThreads: GmailThread[] = [
  {
    id: "ph-thread-1",
    subject: "CTD Done On Apr 29, 2026 12:00 PM",
    snippet:
      "MySigrid Internal IT Support <support@mysigrid.ai> wrote: Hi James, this is a confirmation that your critical task drill has been completed.",
    participants: [
      { name: "James MySigrid Mail", email: "james@mysigrid.example" },
    ],
    unread: false,
    latestDraftOrMessageDate: t(-60 * 30),
  },
  {
    id: "ph-thread-2",
    subject: "Critical Task Drill for Sales And Marketing",
    snippet:
      "Hi Chelsie Padilla, this is a Critical Task Drill for Sales And Marketing. To confirm receipt, please reply to this email…",
    participants: [{ email: "support@mysigrid.ai" }],
    unread: false,
    latestDraftOrMessageDate: t(-60 * 60),
  },
  {
    id: "ph-thread-3",
    subject: "Renewal proposal — let's discuss",
    snippet:
      "Hi team — circling back on the proposal we shared last week. Happy to jump on a quick call to walk through the changes.",
    participants: [
      { name: "James Fuentes", email: "james.fuentes@globex.example" },
    ],
    unread: false,
    latestDraftOrMessageDate: t(-60 * 60 * 3),
  },
  {
    id: "ph-thread-4",
    subject: "Critical Task Drill for Nora Chetouani",
    snippet:
      "Hi Wellia Colis, This is a Critical Task Drill for Nora Chetouani. To confirm receipt please reply with the agreed timeline…",
    participants: [{ email: "support@mysigrid.ai" }],
    unread: false,
    latestDraftOrMessageDate: t(-60 * 60 * 8),
  },
  {
    id: "ph-thread-5",
    subject: "New booking request",
    snippet:
      "On Apr 29, 2026 3:00 AM, MySigrid Internal IT Support <support@mysigrid.ai> wrote: Hi Clyde, you have a new booking…",
    participants: [
      { name: "Eia Piñon", email: "eia.pinon@hooli.example" },
    ],
    unread: true,
    latestDraftOrMessageDate: t(-60 * 60 * 12),
  },
  {
    id: "ph-thread-6",
    subject: "Re: Q2 reporting deck",
    snippet:
      "Looks great — left a few comments on slides 4 and 9. Otherwise ready to ship.",
    participants: [
      { name: "Vanessa Flores", email: "vanessa@acme.example" },
    ],
    unread: true,
    latestDraftOrMessageDate: t(-60 * 60 * 26),
  },
  {
    id: "ph-thread-7",
    subject: "Onboarding checklist — final pass",
    snippet:
      "Final version attached. Let me know if any of the items need owner reassignment before we hand off.",
    participants: [
      { name: "Miguel Mempin", email: "miguel@initech.example" },
    ],
    unread: false,
    latestDraftOrMessageDate: t(-60 * 60 * 48),
  },
  {
    id: "ph-thread-8",
    subject: "Welcome to MySigrid 👋",
    snippet:
      "Thanks for signing up. Here's a quick tour of what you can do in your first week.",
    participants: [{ email: "team@mysigrid.example" }],
    unread: false,
    latestDraftOrMessageDate: t(-60 * 60 * 72),
  },
];
